web:
  build: .
  dockerfile: Dockerfile-development
  links:
   - db
  ports:
   - "8000:8000"
  volumes:
   - .:/usr/src/app/
  environment:
   NODE_ENV: development 
   MONGO_URL: mongodb://user1:password1@ds237409.mlab.com:37409/make_it_rain
db:
  image: mongo:latest
  ports:
   - "27017:27017"

